# permissions for end users to view jmxexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jmxexporter-viewer-role
rules:
- apiGroups:
  - jmx.f44f.com.jmx.f44f.com
  resources:
  - jmxexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jmx.f44f.com.jmx.f44f.com
  resources:
  - jmxexporters/status
  verbs:
  - get
