apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jmxexporters.jmx.f44f.com
spec:
  group: jmx.f44f.com
  names:
    kind: JmxExporter
    plural: jmxexporters
    singular: jmxexporter
    shortNames:
      - jmxexp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentAnnotationValue:
                  type: string
                  description: "The value of the annotation used for matching Deployments."
                  default: "true"
                enableInjection:
                  type: boolean
                  description: "Whether to enable JMX exporter injection into matching Deployments."
                  default: true
                exposeServicePort:
                  type: boolean
                  description: "Whether to expose a port in the Service for JMX exporter."
                  default: true
                createServiceMonitor:
                  type: boolean
                  description: "Whether to create a ServiceMonitor resource for JMX exporter."
                  default: false
